package com.example.dailypractice2.data.entity

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Data class representing a journal entry entity for database storage.
 *
 * @property id The unique identifier for the journal entry (auto-generated).
 * @property title The title of the journal entry.
 * @property entry The content of the journal entry.
 * @property entryDate The date of the journal entry.
 */
@Entity(tableName = "journal_entries")
data class JournalEntryEntity(
    @PrimaryKey(autoGenerate = true) // The primary key for the table, auto-generated by Room
    val id: Long,
    @ColumnInfo(name = "entry_title")
    val title: String,
    @ColumnInfo(name = "entry_content")
    val entry: String,
    @ColumnInfo(name = "entry_date")
    val entryDate: String,
)
